server:
  port: 8011
  tomcat:
    access-log-pattern: checkserver--%h %l %u %t "%r" %s %b (%D ms)
    # log pattern of the access log
    access-log-enabled: true
    accesslog:
      directory: /opt/deployjars/login/logs/